### ISSUE TITLE
给一个祝福w

### ISSUE THREAD

**Issue by ycMia** [bilibili/bilibili.github.io#1]
>呐呐...在这里留个issue总不过分吧?（成为Tag#plaintext的那种？）

能看到b站官方在github上创建博客实在太好了wwww
(\*´ω｀\*)
我已经能够看到未来更多有意思的开发思路
（甚至例如像技术开发中的趣闻？）从这里萌生啦

依然---为我们的小破站鼓劲---祝越办越好w
## 哔哩哔哩 (゜-゜)つロ 干杯~

**Comment by devcui** [comment]
I want to join this organization,invite me please _(:зゝ∠)_
